require("dotenv").config();  //USAR "DOTENV" PERO SOLO SU MODULO "CONFIG" Y ESTO HARA QUE SI EXISTE UN ARCHIVO AL INICIO DEL PROYECTO LLAMADO ".ENV" LEERA LO QUE TIENE DENTRO Y LO ASIGNARA A LAS VARIABLES DE ENTORNO
// SIEMPRE DEBE IR AL INICIO PARA PODER IR CARGANDO LAS VARIABLES MIENTRAS SE EJECUTA EL RESTO DEL CODIGO


const app = require("./server.js")  //SE SOLICITA USAR EL ARCHIVO SERVER.JS
require("./database.js")

console.log(process.env.TESTING)

app.listen(app.get("port"), () => {   //SE LE ASIGNA UN PUERTO AL SERVIDOR. SE VERIFICARA SI EXISTE UN PUERTO  DE LO CONTRARIO SE LE ASIGNARA EL PREDETERMINADO [A].SERVER
    console.log("El servidor esta conectado", app.get("port"))
})
